version: "2"
services:
  app:
    container_id: af9ea34c4697
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: convergentes
    image: nodejs
    volumes:
      - ./data:/data/db
    ports:
      - "8080:8080"
